fixed the logo disappearing issue in smaller screen sizes and adds the hover on nav-link
NSCC-BPIT/NSCC-BPIT-Website pull request #249
Opened 2023-10-03 18:12 UTC by dev-abhishekkr

This PR fixes the logo disappearing issue in small screen sizes and it
This PR adds the dynamic hover on navigation link.

Earlier the logo used to get disappear in small screen sizes.

![Screenshot (126)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/144001779/1441f463-31c3-49e2-885c-d42c3eba851d)
![Screenshot (127)](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/144001779/2b0471ba-95c8-4d4d-a690-13a8c3031b32)

2023-10-03 18:23 UTC, keshav39 reviewed
this seems ok but what is the hover effect that u added? the hover effect was already there andin mobile view there no hover option

2023-10-03 21:25 UTC, pradeeptosarkar commented
@dev-abhishekkr the build checks are failing, kindly have a look

2023-10-05 06:41 UTC, pradeeptosarkar requested changes
@dev-abhishekkr  the build checks are failing, kindly have a look

2023-10-05 08:32 UTC, keshav39 requested changes
follow these reviews to have the pr accepted

2023-10-05 08:32 UTC, keshav39 commented on src/components/Navbar/Navbar.jsx
> -          <NavbarLink to = "/"><Logo src="./img/logo2.png"></Logo></NavbarLink>
undo to this point and add the required class to this navbarlink @dev-abhishekkr

2023-10-05 08:32 UTC, keshav39 commented on src/components/Navbar/Navbar.jsx
> +          <Logo src="./img/logo2.png"></Logo>
remove these change from the code as they are not necessary

2023-10-05 08:32 UTC, keshav39 commented on src/components/Navbar/Navbar.jsx
> +          <NavLinks className="nav-links">
the check is failing because u have not closed the navlinks here

2023-10-05 11:03 UTC, closed without merging